version: '2'

services:
  application:
    image: tianon/true
    volumes:
      - ./:/app

  php-cli:
    build:
      context: workenv/docker/php-cli
    working_dir: /app
    volumes_from:
      - application
    links:
      - mysql:mysql
    tty: true

  mysql:
    build: workenv/docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    command: [mysqld, --character-set-server=utf8mb4,
      --collation-server=utf8mb4_unicode_ci,
      --default-authentication-plugin=mysql_native_password]

volumes:
  mysql-data:
    driver: local
